name: NuGet Package Release

on:
  push:
    branches: ["main", "master", "production"]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          source-url: https://nuget.pkg.github.com/omoinjm
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: versioning
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: semver
          increment: patch

      - name: Pack the template
        run: dotnet pack "./src/Clean.Architecture.Template.API/Clean.Architecture.Template.API.csproj" --configuration Release --output-directory ./artifacts -p:PackageVersion=${{ steps.versioning.outputs.next_version }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.next_version }}
          release_name: "Release ${{ steps.versioning.outputs.next_version }}"
          body: "Automated release based on recent commits."
          draft: false
          prerelease: false
          files: "./artifacts/*.nupkg"

      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
