name: NuGet Package Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  PROJECT_PATH: "src/Clean.Architecture.Template.API/Clean.Architecture.Template.API.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------------
      # Setup .NET
      # -------------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      # -------------------------------
      # Restore dependencies
      # -------------------------------
      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: Create output directory
        run: mkdir -p ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Pack project"
        run: |
          dotnet pack ${{ env.PROJECT_PATH }} \
            --no-restore \
            --no-build \
            --configuration Release \
            --include-symbols \
            -p:PackageVersion=${{ steps.version.outputs.version-without-v }} \
            --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "NuGet package"
        run: |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg \
            -k ${{ secrets.NUGET_AUTH_TOKEN }} \
            -s ${{ env.NUGET_SOURCE_URL }}

      - name: "GitHub add NuGet package"
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source \
            --username omoinjm \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            https://nuget.pkg.github.com/omoinjm/index.json

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/omoinjm/index.json
